/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [7:0] result;
  
  wire [8-1:0] M_add_sum1;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  reg [6-1:0] M_add_alufn;
  reg [8-1:0] M_add_a;
  reg [8-1:0] M_add_b;
  adder_1 add (
    .alufn(M_add_alufn),
    .a(M_add_a),
    .b(M_add_b),
    .sum1(M_add_sum1),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_add_a[0+7-:8] = io_dip[8+7-:8];
    M_add_b[0+7-:8] = io_dip[0+7-:8];
    M_add_alufn[0+5-:6] = io_dip[16+0+5-:6];
    io_led = io_dip;
    result = M_add_sum1;
    led = result;
  end
endmodule
